### ISSUE TITLE
step 2 could be added to composer 

### ISSUE THREAD

**Issue by mipapo** [aescarcha/oauth#1]
> composer require friendsofsymfony/rest-bundle
> composer require jms/serializer-bundle
> composer require nelmio/api-doc-bundle
> composer require friendsofsymfony/user-bundle
> composer require aescarcha/user-bundle dev-master
> composer require friendsofsymfony/oauth-server-bundle

You could add a require section into your composer.json to let composer automatically get that bundles  ;)

```
    "require": {
        "php": ">=5.3.9",
        "symfony/form": "~2.3|~3.0",
        "symfony/framework-bundle": "~2.3|~3.0",
        "symfony/security-bundle": "~2.3|~3.0",
        "symfony/twig-bundle": "~2.3|~3.0"
    },
```

**Comment by aescarcha** [comment]
Yes, I know this, the thing is that Symfony best prastices for reusable bundles doc says that _A bundle must not embed third-party PHP libraries. It should rely on the standard Symfony autoloading instead._ So that's why it's not used here, maybe you want to use a user bundle that's not `aescarcha/user-bundle`

https://symfony.com/doc/current/bundles/best_practices.html#vendors
